[package]
name = "mips_goggles"
authors = ["xlatbx59"]
repository = "https://github.com/xlatbx59/Mips-goggles"
keywords = ["mips", "disassembler"]
version = "0.1.0"
edition = "2021"

[[example]]
name = "linear_sweep"

[dependencies]
#no dependencies